### PR TITLE
fix: missing authentication credentials for REST request

### PR DESCRIPTION
**Pull request by itest6**
Ping test to Elasticsearch cluster with authentication
Test OK with ES 7.x

### CODE REVIEW

**Comment by deric** [comment]
According to [changelog](url), they've renamed the parameter in 8.0.0.
> Added basic_auth parameter for specifying username and password authentication

But that doesn't apply to this ping.

**Comment by itest6** [comment]
OK. I made some tweaks and it should be fine now

**Comment by deric** [comment]
@itest6 Thanks, looks good! But now we should require `elasticsearc>=8.0.0`, right?

**Comment by itest6** [comment]
Yes, although pip will download the latest version, it is still necessary to specify the minimum version

**Pull request merged**
